### ISSUE TITLE
如何判断软件已经生效？

### ISSUE THREAD

**Issue by Elegantttt** [qhy040404/FxxkMIUIAd#2]
已用shizuku授权，但体感上似乎没有生效，且软件上的两个广告服务仍然显示启用状态。

os 1.0.6.0，安卓14
![Screenshot_2024-04-07-23-01-56-472_com qhy040404 fxxkmiuiad](https://github.com/qhy040404/FxxkMIUIAd/assets/102576364/0b5e8193-963e-4a43-baa9-e1c4f747af08)

**Comment by Elegantttt** [comment]
点击禁用以后直接闪退

**Comment by qhy040404** [comment]
看样子高版本系统api有变更，明天再修修（

**Comment by qhy040404** [comment]
我用14pro，os1.0.6.0，a14复现不出来，你是什么机型

**Comment by Elegantttt** [comment]
> 我用14pro，os1.0.6.0，a14复现不出来，你是什么机型

![Screenshot_2024-04-08-10-01-36-585_com android settings](https://github.com/qhy040404/FxxkMIUIAd/assets/102576364/68da5711-b32f-47be-a913-f671dc1ce235)

**Comment by qhy040404** [comment]
澎湃好像把快应用和开屏广告加进系统应用列表里面了，adb的权限不够
![image](https://github.com/qhy040404/FxxkMIUIAd/assets/45379733/8471fcdb-f6d4-4aee-8385-024e3da6fa1a)

**Comment by qhy040404** [comment]
要强行禁用只能hook com.android.server.pm.PackageManagerServiceImpl的`canBeDisabled`函数，单纯使用shizuku做不到的

**Comment by Elegantttt** [comment]
原来如此，感觉自己的手机越来越没有控制权了🤔
感谢解惑

**Comment by qhy040404** [comment]
有一个其他的方案，只不过使用中可能会有提示框
![image](https://github.com/qhy040404/FxxkMIUIAd/assets/45379733/968dca77-698a-444e-84c7-402b04c7b3cd)

**Comment by Elegantttt** [comment]
> 有一个其他的方案，只不过使用中可能会有提示框 ![image](https://private-user-images.githubusercontent.com/45379733/320338616-968dca77-698a-444e-84c7-402b04c7b3cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDQxNTcsIm5iZiI6MTcxMjU0Mzg1NywicGF0aCI6Ii80NTM3OTczMy8zMjAzMzg2MTYtOTY4ZGNhNzctNjk4YS00NDRlLTg0YzctNDAyYjA0YzdiM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAyMzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYWI3MmE0Nzk1M2JhYTA1Mzg0YTA0NGNiMWM3MzA5Mjg1NmFmZmE3YjI4NDdlZTE5ZjEwNjFiZjk0ODM2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DECLX7mAayJgu04FCYI4jY3g86asj8AoW0aOPybmb4Y)

看上去似乎也可以接受

**Comment by qhy040404** [comment]
suspend api unaccessable

**Comment by Elegantttt** [comment]
> suspend api unaccessable

![Screenshot_2024-04-13-04-19-25-476_in sunilpaulmathew ashell](https://github.com/qhy040404/FxxkMIUIAd/assets/102576364/6c99e334-b23f-4084-a51c-a6b70b561ef9)
还是一点禁用就会闪退

**Comment by qhy040404** [comment]
suspend只能通过shell去设置，api访问不了，可能会更新一下显示吧，suspend软件内操作是不太可能了

**Comment by Elegantttt** [comment]
> suspend只能通过shell去设置，api访问不了，可能会更新一下显示吧，suspend软件内操作是不太可能了

![Screenshot_2024-04-13-06-40-41-260_com android browser](https://github.com/qhy040404/FxxkMIUIAd/assets/102576364/c65b4cfa-9861-49b4-b96e-f898d0e6880b)
![Screenshot_2024-04-13-06-40-56-383_com shizuku uninstaller](https://github.com/qhy040404/FxxkMIUIAd/assets/102576364/f6a2f700-011d-4205-8111-c3be07e081ed)
也就是说shizuku runner也不行？必须用电脑adb？

**Comment by qhy040404** [comment]
能操作shell就行，不一定非要电脑，主要现在软件没做识别suspend

**Comment by Elegantttt** [comment]
> 能操作shell就行，不一定非要电脑，主要现在软件没做识别suspend

好吧～我试了ashell和shizuku runner，好像都是不行的

**Comment by qhy040404** [comment]
suspend在设置里是不显示的，你可以通过去应用商店找一个快应用尝试打开看有没有生效

**Comment by qhy040404** [comment]
过两天可能发版吧，这两天太忙了，到时候尽量把suspend也加进来
