### ISSUE TITLE
POCO X6 5G HyperOS

### ISSUE THREAD

**Issue by MAXMILLI0N** [qhy040404/FxxkMIUIAd#3]
Hi, It's not working on 

> POCO X6 5G HYPEROS ANDROID 14
The app not opening at all
![Screenshot_2024-04-22-20-28-49-394_com mi android globallauncher](https://github.com/qhy040404/FxxkMIUIAd/assets/62308127/52f51c80-c0fd-4d9b-b8b2-08a48abf3b42)

**Comment by qhy040404** [comment]
Maybe you should take the screenshot of the summary instead of this useless one :(

**Comment by MAXMILLI0N** [comment]
> Maybe you should take the screenshot of the summary instead of this useless one :(

"summary" 🤓 does not open for me and the app 
 Works when i deactivate Shizuku but it won't work if i activate Shizuku.

**Comment by qhy040404** [comment]
can you check if your system contains these packages?
```
"com.miui.rom"
"com.miui.hybrid"
"com.miui.systemAdSolution"
```

**Comment by MAXMILLI0N** [comment]
Only 
"com.miui.rom"

**Comment by qhy040404** [comment]
that makes sense. Maybe the advertising software package for the international version of the system is different from the Chinese version.

**Comment by qhy040404** [comment]
Unless someone tells me the name of the AD package for the international system, I can't help.
i can't help unless someone tells me the ad's package name for the international version of the system. 😢

**Comment by MAXMILLI0N** [comment]
I found out why i cant view the "summary" 💀.
I disabled the bug report app with the rest of the Google/Xiaomi apps 😀.

https://ibb.co/BTs0Ry3

**Comment by MAXMILLI0N** [comment]
People say that "com.miui.msa.global" is the ADs main source.
