### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by mzxjiang** [qhy040404/FxxkMIUIAd#4]
如题，点击软件图标后会播放软件打开动画，紧接着播放软件关闭动画，没有出现任何有用信息，没有提示应用闪退，也没有错误信息。
系统版本如图。
![Screenshot_2024-09-05-17-58-51-259_com android settings-edit](https://github.com/user-attachments/assets/06e1557c-f767-4a01-af36-17aa1fa63362)

**Comment by qhy040404** [comment]
hyperos这个已经废啦，那几个流氓直接变成system不能通过adb修改了

**Comment by mzxjiang** [comment]
所以只能用命令suspend了吗？
________________________________

**Comment by qhy040404** [comment]
目前是这样的哦

**Comment by qhy040404** [comment]
> 如题，点击软件图标后会播放软件打开动画，紧接着播放软件关闭动画，没有出现任何有用信息，没有提示应用闪退，也没有错误信息。 系统版本如图。 ![Screenshot_2024-09-05-17-58-51-259_com android settings-edit](https://private-user-images.githubusercontent.com/180525020/364723960-06e1557c-f767-4a01-af36-17aa1fa63362.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njk1NDMsIm5iZiI6MTcyNTY2OTI0MywicGF0aCI6Ii8xODA1MjUwMjAvMzY0NzIzOTYwLTA2ZTE1NTdjLWY3NjctNGEwMS1hZjM2LTE3YWExZmE2MzM2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMDM0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGEwMDFiOTExZjRkZjk4MzRmNTI0MzhiYzA1ZjMzMWFjMjE3MGIxMjA1YzdlNGVkMjVmM2QzN2FmNzEwNWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xKbS6hAX9wS1kLrlIcexEnSGldCQrIWs-QH2Cwerj80)

你是已经shizuku授权后直接关闭吗

**Comment by mzxjiang** [comment]
> > 如题，点击软件图标后会播放软件打开动画，紧接着播放软件关闭动画，没有出现任何有用信息，没有提示应用闪退，也没有错误信息。系统版本如图。![Screenshot_2024-09-05-17-58-51-259_com Android 设置-编辑](https://private-user-images.githubusercontent.com/180525020/364723960-06e1557c-f767-4a01-af36-17aa1fa63362.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njk1NDMsIm5iZiI6MTcyNTY2OTI0MywicGF0aCI6Ii8xODA1MjUwMjAvMzY0NzIzOTYwLTA2ZTE1NTdjLWY3NjctNGEwMS1hZjM2LTE3YWExZmE2MzM2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwMDM0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGEwMDFiOTExZjRkZjk4MzRmNTI0MzhiYzA1ZjMzMWFjMjE3MGIxMjA1YzdlNGVkMjVmM2QzN2FmNzEwNWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xKbS6hAX9wS1kLrlIcexEnSGldCQrIWs-QH2Cwerj80)
> 
> 你是已经shizuku授权后直接关闭吗

是的，已在shizuku里授权。
应用仍然无法启动。

**Comment by qhy040404** [comment]
可以尝试新版本 [1.3.0](https://github.com/qhy040404/FxxkMIUIAd/releases/tag/1.3.0)

**Comment by mzxjiang** [comment]
1.3.0版本各项功能已经正常。
可以问一下不能启动是什么原因吗？

**Comment by qhy040404** [comment]
在activity create之前调用getPackageManger导致null了
